### ISSUE TITLE
To do

### ISSUE THREAD

**Issue by stratixx** [EiTI-18L-TMLab/Lab5#1]
1. Konfiguracja UART do komunikacji z PC

- Osiągnięcie komunikacji TX do RX - sam do siebie - WYKONANE

- Osiągnięcie dwukierunkowej komunikacji MSP do PC - WYKONANE

- Implementacja echa terminala

2. Implementacja buforów dla danych odbieranych i wysyłanych oraz może aplikacji -WYKONANE

3. Kopiowanie ciągu znaków z bufora odbioru do bufora(tablicy) aplikacji i odwrotnie przy użyciu DMA - REZYGNACJA Z REALIZACJI DMA

4. Funkcja formatująca tekst podany jako argument oraz zwracająca tekst sformatowany. - WYKONANE

**Comment by kubasikora** [comment]
Co do konfiguracji UARTA to cos jest nie tak z nazwami, sprawdzic to

**Comment by stratixx** [comment]
Modyfikacja treści zadania - zmiana buforów cyklicznych na dowolne bufory.

**Comment by stratixx** [comment]
Wykonany punkt 4, pliki dostępne w katalogu aplikacji jako _**format**_

**Comment by stratixx** [comment]
Dodalem znaleziony i dzialajacy projekt z konfiguracja uart

**Comment by kubasikora** [comment]
Loopback to jest set jednego bitu LISTEN (BIT 3) w UxCTL

**Comment by stratixx** [comment]
Zadanie wykonane, mój opis aplikacji jest już w drodze

**Comment by stratixx** [comment]
Dodany opis aplikacji oraz buforów cyklicznych, czekam na rozwiązanie wątku implementacji echa terminala

**Comment by kubasikora** [comment]
echo done
